# Edit via `hyprshell config edit`, generate via `hyprshell config generate`
version = 3

[windows]
scale = 8.5
items_per_row = 5

[windows.overview]
key = "s"
modifier = "alt"
filter_by = []
hide_filtered = false

[windows.overview.launcher]
default_terminal = "alacritty"
launch_modifier = "ctrl"
width = 650
max_items = 5
show_when_empty = true

[windows.overview.launcher.plugins.applications]
run_cache_weeks = 4
show_execs = true
show_actions_submenu = true

[[windows.overview.launcher.plugins.websearch.engines]]
url = "https://www.twitch.tv/search?term={}"
name = "Twitch"
key = "t"

[[windows.overview.launcher.plugins.websearch.engines]]
url = "https://www.youtube.com/results?search_query={}"
name = "YouTube"
key = "y"

[[windows.overview.launcher.plugins.websearch.engines]]
url = "https://www.reddit.com/search?q={}"
name = "Reddit"
key = "r"

[[windows.overview.launcher.plugins.websearch.engines]]
url = "https://github.com/{}"
name = "Github"
key = "g"

[[windows.overview.launcher.plugins.websearch.engines]]
url = "https://www.google.com/search?q={}"
name = "Google"
key = "s"

[windows.overview.launcher.plugins.calc]

[windows.overview.launcher.plugins.path]

[windows.overview.launcher.plugins.actions]
actions = [
    "lock_screen",
    "hibernate",
    "logout",
    "reboot",
    "shutdown",
    "suspend",
    { custom = { names = [
    "Kill",
    "Stop",
], details = "Kill or stop a process by name", command = 'pkill "{}" && notify-send hyprshell "stopped {}"', icon = "remove" } },
    { custom = { names = ["Reload Hyprshell"], details = "Reload Hyprshell", command = """sleep 1; hyprshell socat '"Restart"'""", icon = "system-restart" } },
]
